//! FR-086 — the W3C trace-context parser under property-based fuzzing.
//!
//! # What the property test proves that the unit tests cannot
//!
//! The unit tests pin each rule with one structured mutant. That says the parser refuses the
//! inputs the author thought of. Ten thousand random inputs, plus random single-byte mutations
//! of a valid header, say something else: **no input panics, no accepted input renders to
//! anything but its outbound form — itself, with every flag bit this version does not define set
//! to zero — and a valid header stays valid under exactly the mutations the specification permits
//! and no others.**
//!
//! Four properties, each with its own strategy:
//!
//! 1. **Totality** — arbitrary bytes up to 4 KiB never panic and are refused or accepted, nothing
//!    else.
//! 2. **Round trip** — a valid header, generated field by field from the grammar, parses to the
//!    generated bytes (the received flags byte included) and re-renders as its outbound form:
//!    §3.2.2.5.2 *"Vendors MUST set those to zero"*, §4.3 *"Vendors will set all unparsed /
//!    unknown trace-flags to 0 on outgoing requests"*. The first version asserted a byte-identical
//!    round trip, which pinned the defect (Phase 010 correction round, Finding 4).
//! 3. **Defined bits round-trip** — a header whose flags carry only the `sampled` bit, or nothing,
//!    re-renders byte-identically: the positive control that the masking is targeted.
//! 4. **Single-byte mutation** — replacing one byte of a valid header with a random byte is
//!    accepted only when the replacement is itself a lowercase hex digit in a hex position (or
//!    the same delimiter in a delimiter position) and does not zero an identifier. That is the
//!    whole grammar stated as a predicate, and the parser must agree with it on every sample.

use proptest::prelude::*;
use renvor_core::observe::trace_context::{
    MAX_TRACESTATE_BYTES, TRACEPARENT_LEN, TraceContext, TraceState, parse_traceparent,
};

fn hex_lower(bytes: &[u8]) -> String {
    bytes.iter().map(|byte| format!("{byte:02x}")).collect()
}

fn non_zero_bytes(len: usize) -> impl Strategy<Value = Vec<u8>> {
    prop::collection::vec(any::<u8>(), len).prop_filter("all zeroes is invalid", |bytes| {
        bytes.iter().any(|byte| *byte != 0)
    })
}

fn valid_header() -> impl Strategy<Value = (Vec<u8>, Vec<u8>, u8, String)> {
    (non_zero_bytes(16), non_zero_bytes(8), any::<u8>()).prop_map(|(trace, parent, flags)| {
        let header = format!(
            "00-{}-{}-{}",
            hex_lower(&trace),
            hex_lower(&parent),
            hex_lower(&[flags])
        );
        (trace, parent, flags, header)
    })
}

/// A valid header whose flags carry the `sampled` bit or nothing: no undefined bit to zero.
fn sampled_only_header() -> impl Strategy<Value = String> {
    (non_zero_bytes(16), non_zero_bytes(8), any::<bool>()).prop_map(|(trace, parent, sampled)| {
        format!(
            "00-{}-{}-{:02x}",
            hex_lower(&trace),
            hex_lower(&parent),
            u8::from(sampled)
        )
    })
}

/// The outbound form the specification requires of a valid header: the first 53 bytes as they
/// were, then the flags with every bit this version does not define set to zero (§3.2.2.5.2
/// *"Vendors MUST set those to zero"*; §4.3 *"Vendors will set all unparsed / unknown trace-flags
/// to 0 on outgoing requests"*). Stated independently of the parser so the parser is checked
/// against the rule rather than against itself.
fn outbound_form(header: &str) -> String {
    let flags =
        u8::from_str_radix(&header[53..55], 16).expect("a valid header ends in two hex digits");
    format!("{}{:02x}", &header[..53], flags & 0x01)
}

/// The grammar as a predicate over one mutated position, so the parser can be checked against
/// an independent statement of the rules rather than against itself.
fn mutation_should_parse(header: &[u8], position: usize, replacement: u8) -> bool {
    let is_delimiter = matches!(position, 2 | 35 | 52);
    if is_delimiter {
        return replacement == b'-';
    }
    if position < 2 {
        // The version bytes must stay exactly `00`.
        return replacement == b'0';
    }
    if !(replacement.is_ascii_digit() || (b'a'..=b'f').contains(&replacement)) {
        return false;
    }
    let mut mutated = header.to_vec();
    mutated[position] = replacement;
    let trace_zero = mutated[3..35].iter().all(|byte| *byte == b'0');
    let parent_zero = mutated[36..52].iter().all(|byte| *byte == b'0');
    !trace_zero && !parent_zero
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(10_000))]

    #[test]
    fn arbitrary_bytes_never_panic_and_are_never_partially_accepted(
        input in prop::collection::vec(any::<u8>(), 0..4096)
    ) {
        // `from_utf8_lossy` keeps the strategy over bytes, which is what a header is; the parser
        // takes `&str` because HTTP already refused non-text at the transport.
        let text = String::from_utf8_lossy(&input);
        if let Ok(context) = parse_traceparent(&text) {
            prop_assert_eq!(text.len(), TRACEPARENT_LEN);
            prop_assert_eq!(context.render_traceparent(), outbound_form(&text));
        }
        // tracestate: never panics, never longer than the bound when accepted.
        if let Some(state) = TraceState::parse(&text) {
            prop_assert!(state.as_str().len() <= MAX_TRACESTATE_BYTES);
        }
    }

    #[test]
    fn a_grammar_generated_header_round_trips_to_its_own_bytes(
        (trace, parent, flags, header) in valid_header()
    ) {
        let context = parse_traceparent(&header).expect("grammar-generated headers are valid");
        let trace_bytes = context.trace_id().as_bytes().to_vec();
        let parent_bytes = context.parent_id().as_bytes().to_vec();
        prop_assert_eq!(trace_bytes, trace);
        prop_assert_eq!(parent_bytes, parent);
        prop_assert_eq!(
            context.flags().as_byte(),
            flags,
            "the inbound record is the received byte"
        );
        prop_assert_eq!(context.render_traceparent(), outbound_form(&header));
        // With a tracestate too, and the tracestate never changes the traceparent verdict.
        let with_state = TraceContext::parse(&header, Some("rojo=00f067aa0ba902b7")).unwrap();
        prop_assert_eq!(with_state.render_traceparent(), outbound_form(&header));
        prop_assert!(with_state.state().is_some());
    }

    #[test]
    fn a_header_carrying_only_defined_flag_bits_round_trips_byte_identically(
        header in sampled_only_header()
    ) {
        // POSITIVE CONTROL for the masking: with no undefined bit set there is nothing to zero,
        // so the outbound form is the input itself, and the parser agrees.
        prop_assert_eq!(outbound_form(&header), header.clone());
        let context = parse_traceparent(&header).expect("grammar-generated headers are valid");
        prop_assert_eq!(context.render_traceparent(), header);
    }

    #[test]
    fn a_single_byte_mutation_is_accepted_exactly_when_the_grammar_says_so(
        (_, _, _, header) in valid_header(),
        position in 0_usize..TRACEPARENT_LEN,
        replacement in any::<u8>()
    ) {
        let mut mutated = header.clone().into_bytes();
        mutated[position] = replacement;
        let expected = mutation_should_parse(header.as_bytes(), position, replacement);
        let text = String::from_utf8_lossy(&mutated).to_string();
        let observed = parse_traceparent(&text).is_ok();
        prop_assert_eq!(
            observed,
            expected,
            "position {} replacement {:#04x}: header {}",
            position,
            replacement,
            text
        );
    }
}
