//! Transport errors, and the boundary that keeps causes out of responses.
//!
//! # Two audiences, two renderings
//!
//! An error here is read by two parties with opposite needs. The operator needs the cause; the
//! caller must not have it. So [`HttpError`] carries a **detail** that reaches telemetry and a
//! **status** that reaches the wire, and the two are separate fields rather than one string that
//! someone remembers not to send.
//!
//! [`HttpError::public_message`] is what a caller sees, and it is derived from the **kind** alone.
//! It cannot include the detail, because it never receives it.
//!
//! # The detail is a closed set, and it was not always — corrected 2026-08-27
//!
//! `HttpError::new` used to take `detail: impl Into<String>`. The separation above was real, and
//! it was also the whole defence: the operator-facing string was **unbounded runtime text supplied
//! by the application author**, and it went to `tracing` by design. An author writing
//!
//! ```text
//! HttpError::new(HttpErrorKind::StateUnavailable, format!("could not reach {dsn}"))
//! ```
//!
//! put a DSN into telemetry, and nothing in the type, the tests, or the contract objected.
//! `CONSTITUTION.md` principle VI forbids secrets in telemetry and **exempts no consumer** — the
//! same rule that withdrew the database adapters' `driver_error` fields in this phase's second
//! correction round, applied to the site that round reported as out of scope.
//!
//! The channel is now closed at the **type**: [`HttpErrorDetail`] is a fieldless enum generated by
//! the `closed_named_enum!` declaration below, so there is no parameter a runtime string can
//! arrive in and no variant a maintainer can add that would carry one. `&'static str` would not have been
//! enough — `Box::leak` promotes any `String` to `&'static str`, so a lifetime is not a
//! provenance.
//!
//! Every consumer of the detail — telemetry, [`Display`](fmt::Display), the error source chain,
//! and the response body — can therefore only ever render one of the reviewed literals below.

use core::fmt;

/// Declares a fieldless enum together with `ALL` and `as_str`, from a single list.
///
/// # Why this is a local macro rather than a shared one
///
/// `renvor-database` carries the same construction, and the two **cannot be shared**. It declares
/// no dependency on `renvor-core` — `xtask` step 7 asserts that absence against the resolved graph
/// with a positive control — and this crate reaching `renvor-database` would breach the
/// transport/persistence isolation the same step asserts. There is no crate below both.
///
/// It was briefly placed in `renvor-core` and imported here. That resolved in a workspace build and
/// **failed in `cargo package --workspace` verification**, where the packaged transport could not
/// see the kernel's exported macro; the macro itself was proven correct against both the packaged
/// and the extracted kernel by isolation probes, and the interaction was not identified. Rather
/// than carry a gate failure nobody could explain, or add a `#[macro_export]` to the kernel's
/// public surface for one consumer, the declaration lives here — where it needs no cross-crate
/// resolution at all.
///
/// # The mutation this exists to make unrepresentable
///
/// A closed enum written by hand is several authorities that can disagree. `renvor-database`
/// learned it the expensive way: its `DatabaseAdapter` survived a mutation (**M-24b**) that added
/// `Custom(&'static str)` and left every test green, because a catch-all-free `match` forces an
/// author to *handle* a new variant, not to handle it *safely* — returning the carried string
/// satisfies the compiler.
///
/// Written once here, a **unit** variant is added in one reviewed line, and a **data-bearing**
/// variant does not match `$variant:ident` and is a macro error before it is anything else. That
/// is what stops the next maintainer re-opening the channel `HttpError::new`'s signature closes.
/// **M-41** is that mutation, run against this declaration.
macro_rules! closed_named_enum {
    (
        $(#[$enum_meta:meta])*
        $vis:vis enum $name:ident {
            $(
                $(#[$variant_meta:meta])*
                $variant:ident => $rendered:literal
            ),+ $(,)?
        }
    ) => {
        $(#[$enum_meta])*
        #[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
        #[non_exhaustive]
        $vis enum $name {
            $(
                $(#[$variant_meta])*
                $variant,
            )+
        }

        impl $name {
            /// Every variant, in declaration order.
            ///
            /// Generated from the same list as the enum itself, so it cannot fall behind it.
            pub const ALL: [Self; <[()]>::len(&[$(closed_named_enum!(@unit $variant)),+])] =
                [$(Self::$variant),+];

            /// The variant's reviewed name.
            ///
            /// Every arm returns a literal written at the declaration. No value derived from
            /// configuration, a caller, or a request can reach the returned string.
            #[must_use]
            pub const fn as_str(self) -> &'static str {
                match self {
                    $(Self::$variant => $rendered,)+
                }
            }
        }
    };

    // Internal: one `()` per variant, so `ALL`'s length is counted rather than restated.
    (@unit $variant:ident) => {
        ()
    };
}

closed_named_enum! {
    /// Why a request was refused, at the granularity an **operator** is allowed to know.
    ///
    /// # Closed, and closed at the declaration
    ///
    /// One variant per refusal site in this crate. A site that needs a new reason adds a variant
    /// and its reviewed literal in one line; a site that wants to interpolate a value cannot,
    /// because there is nowhere to put it.
    ///
    /// That is deliberate and it is a real cost: an operator reading `drain_in_progress` does not
    /// learn which operation was draining. The cost is paid because the alternative — a free
    /// string chosen at the call site — is how a DSN, a filesystem path, or a header value reaches
    /// a log, and a telemetry record is not a place to find out.
    ///
    /// Where richer diagnosis is genuinely needed it belongs in a **structured field of its own**,
    /// reviewed on its own terms, not appended to this one.
    pub enum HttpErrorDetail {
        /// The `Host` header was absent, or more than one was sent.
        HostHeaderAbsentOrRepeated => "host header absent or repeated",
        /// The host is well-formed but not in the configured set.
        HostNotConfigured => "host is not in the configured set",
        /// The origin header could not be read as a value.
        OriginUnreadable => "origin is not a readable value",
        /// The origin is well-formed but not in the configured set.
        OriginNotConfigured => "origin is not in the configured set",
        /// No route declares the requested path.
        NoRouteDeclared => "no route declares this path",
        /// The concurrency ceiling was reached; the request was not queued.
        ConcurrencyCeilingReached => "concurrency ceiling reached",
        /// Shutdown has begun, so the request was refused rather than admitted.
        ///
        /// **The kernel's own error is discarded rather than rendered.** This is the site that
        /// used to call `error.to_string()`, and `KernelError::ShuttingDown` carries an
        /// `operation: String` whose value is chosen by whoever called the gate.
        DrainInProgress => "shutdown has begun; the request was not admitted",
        /// Request-identifier generation could not obtain entropy.
        EntropyUnavailable => "entropy unavailable for request-identifier generation",
        /// The router was served without connection information.
        ConnectInfoMissing => "no connection information; the router was not served with connect info",
        /// The request exceeded the configured timeout.
        TimeoutElapsed => "request exceeded the configured timeout",
        /// The request body exceeded the configured limit.
        BodyLimitExceeded => "request body exceeded the configured limit",
        /// The request body could not be read to completion, for a reason other than its size.
        BodyReadInterrupted => "the request body could not be read to completion",
        /// A handler panicked and was contained.
        ///
        /// The panic payload is **not** carried. A payload is arbitrary application text and is
        /// exactly the sort of value this enum exists to keep out of a log.
        HandlerPanicked => "the handler panicked; the payload is deliberately not recorded",
    }
}

/// What went wrong, at the granularity a caller is allowed to know.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub enum HttpErrorKind {
    /// The `Host` header was absent, malformed, or not configured.
    HostRejected,
    /// The request body exceeded the configured limit.
    BodyTooLarge,
    /// The request exceeded the configured timeout.
    TimedOut,
    /// The application is draining, or is at its concurrency ceiling.
    Unavailable,
    /// The origin is not permitted by the CORS policy.
    OriginRejected,
    /// Required application state was missing or of an incompatible type.
    StateUnavailable,
    /// A handler panicked and was contained.
    HandlerFailed,
    /// No route declares the requested path.
    ///
    /// A `404` is a refusal like any other here, rather than a response the library produces on
    /// its own — which is what lets it carry a request identifier and be refused during drain.
    NotFound,
    /// The request body could not be read to completion, for a reason other than its size.
    ///
    /// Separate from [`HttpErrorKind::BodyTooLarge`] because they are different events: one is a
    /// caller sending more than the limit, the other is a connection failing part-way. Reporting
    /// the second as `413` told operators their clients were oversending when the clients had in
    /// fact gone away.
    BodyUnreadable,
}

impl HttpErrorKind {
    /// The HTTP status for this kind.
    #[must_use]
    pub const fn status(self) -> u16 {
        match self {
            Self::HostRejected | Self::OriginRejected => 400,
            Self::BodyTooLarge => crate::limits::STATUS_PAYLOAD_TOO_LARGE,
            Self::TimedOut => crate::limits::STATUS_REQUEST_TIMEOUT,
            Self::Unavailable => crate::limits::STATUS_UNAVAILABLE,
            Self::StateUnavailable | Self::HandlerFailed => 500,
            Self::NotFound => 404,
            // The request was not completed and the fault is the caller's connection, not the
            // application's. 400 rather than 500 for the same reason a malformed request is.
            Self::BodyUnreadable => 400,
        }
    }

    /// The stable code an operator can match on.
    #[must_use]
    pub const fn code(self) -> &'static str {
        match self {
            Self::HostRejected => "host_rejected",
            Self::BodyTooLarge => "body_too_large",
            Self::TimedOut => "request_timeout",
            Self::Unavailable => "unavailable",
            Self::OriginRejected => "origin_rejected",
            Self::StateUnavailable => "state_unavailable",
            Self::HandlerFailed => "handler_failed",
            Self::NotFound => "not_found",
            Self::BodyUnreadable => "body_unreadable",
        }
    }
}

/// A transport failure.
///
/// `Copy`, which it could not be while the detail was a `String`. Worth noting rather than
/// hiding: the type became cheaper as a side effect of becoming safe, because the thing it stopped
/// carrying was an owned allocation of arbitrary size.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct HttpError {
    kind: HttpErrorKind,
    /// **Never reaches a response.** Operator-facing only, and drawn from a closed set.
    detail: HttpErrorDetail,
}

impl HttpError {
    /// Builds an error whose `detail` is for operators and never for callers.
    ///
    /// # `detail` is an enum, not a string, and that is the security property
    ///
    /// This signature used to be `detail: impl Into<String>`. Every value it now accepts is one of
    /// [`HttpErrorDetail`]'s reviewed literals, so there is no argument position through which a
    /// DSN, a path, a header value, or a panic payload can reach telemetry.
    #[must_use]
    pub const fn new(kind: HttpErrorKind, detail: HttpErrorDetail) -> Self {
        Self { kind, detail }
    }

    /// The kind.
    #[must_use]
    pub const fn kind(&self) -> HttpErrorKind {
        self.kind
    }

    /// The status to send.
    #[must_use]
    pub const fn status(&self) -> u16 {
        self.kind.status()
    }

    /// The operator-facing detail. **Do not put this in a response.**
    ///
    /// Returns the enum rather than a string. A caller that wants text calls
    /// [`HttpErrorDetail::as_str`] and gets one of the reviewed literals; there is no rendering
    /// path that produces anything else.
    #[must_use]
    pub const fn detail(&self) -> HttpErrorDetail {
        self.detail
    }

    /// What a caller is told.
    ///
    /// Derived from [`HttpErrorKind`] **alone**. This function does not read `self.detail`, so a
    /// path leak or a configuration value cannot reach a response even if one is in the detail —
    /// which is the point of separating them.
    #[must_use]
    pub const fn public_message(&self) -> &'static str {
        match self.kind {
            HttpErrorKind::HostRejected => "the request host is not served by this application",
            HttpErrorKind::BodyTooLarge => "the request body exceeds the configured limit",
            HttpErrorKind::TimedOut => "the request exceeded the configured timeout",
            HttpErrorKind::Unavailable => "the application is not accepting requests",
            HttpErrorKind::OriginRejected => "the request origin is not permitted",
            HttpErrorKind::StateUnavailable | HttpErrorKind::HandlerFailed => {
                "the request could not be completed"
            }
            HttpErrorKind::NotFound => "no route is declared for this path",
            HttpErrorKind::BodyUnreadable => "the request body could not be read",
        }
    }
}

impl fmt::Display for HttpError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // Both halves are `&'static str` chosen at a declaration in this file. `Display` is a
        // rendering path like any other, and it is reachable from `{}` on a boxed `dyn Error`.
        write!(f, "{}: {}", self.kind.code(), self.detail.as_str())
    }
}

impl core::error::Error for HttpError {}

#[cfg(test)]
mod tests {
    use super::{HttpError, HttpErrorDetail, HttpErrorKind};

    /// The words a leak would be made of. None may appear in any rendering of any error.
    ///
    /// Two are drawn from the example that used to be in this file — a real filesystem path and
    /// the word `password` — because that example was written to show the boundary working while
    /// the constructor that produced it was the hole.
    const FORBIDDEN: [&str; 6] = [
        "/srv",
        "password",
        "postgres://",
        "Bearer ",
        "hunter2",
        "db.toml",
    ];

    /// FR-041. A caller is told the kind and nothing else.
    ///
    /// # Why this test no longer plants a secret
    ///
    /// It used to build the detail from `"/srv/app/secrets/db.toml missing key `password`"` and
    /// assert the public message did not contain it. That assertion still held on the day it was
    /// written, and it was measuring the wrong boundary: the string reached **telemetry**, which
    /// `refuse` emitted by design, and no test looked there.
    ///
    /// The string is not planted here because it can no longer be constructed. `HttpError::new`
    /// takes an [`HttpErrorDetail`], and the assertion below is over **every** variant rather than
    /// over one example.
    #[test]
    fn no_public_message_or_detail_can_carry_a_secret() {
        for (index, detail) in HttpErrorDetail::ALL.into_iter().enumerate() {
            for kind in [
                HttpErrorKind::StateUnavailable,
                HttpErrorKind::HandlerFailed,
                HttpErrorKind::Unavailable,
            ] {
                let error = HttpError::new(kind, detail);
                // Every rendering path this type offers, in one place: the caller-facing message,
                // the operator-facing detail, `Display`, and `Debug`.
                let rendered = format!(
                    "{} {} {error} {error:?}",
                    error.public_message(),
                    error.detail().as_str()
                );
                for leak in FORBIDDEN {
                    // The variant is named by INDEX and the rendering is not printed. A failure
                    // here means a redaction regression, and that is the one run in which putting
                    // the offending text into the test log matters most.
                    assert!(
                        !rendered.contains(leak),
                        "a rendering of variant {index} carried a forbidden term"
                    );
                }
            }
        }
    }

    /// POSITIVE CONTROL for the test above, which is otherwise satisfied by rendering nothing.
    ///
    /// A type whose every accessor returned an empty string would pass every assertion there. So
    /// this requires the detail to be present, non-empty, and **distinct per variant** — the
    /// operator-facing value has to still be worth reading.
    #[test]
    fn the_detail_is_still_present_distinct_and_reaches_display() {
        let mut seen: Vec<&str> = Vec::new();
        for (index, detail) in HttpErrorDetail::ALL.into_iter().enumerate() {
            let text = detail.as_str();
            assert!(!text.is_empty(), "variant {index} renders as nothing");
            assert!(
                !seen.contains(&text),
                "variant {index} renders identically to an earlier one, so telemetry cannot tell \
                 the two refusals apart"
            );
            seen.push(text);

            let error = HttpError::new(HttpErrorKind::Unavailable, detail);
            assert_eq!(error.detail(), detail, "the detail is not carried");
            assert!(
                error.to_string().contains(text),
                "`Display` dropped the detail, so the redaction assertions above are vacuous"
            );
            assert!(
                error.to_string().contains(error.kind().code()),
                "`Display` dropped the code"
            );
        }
        let count = seen.len();
        assert!(
            count >= 13,
            "the enum lost variants; {count} remain and every refusal site in this crate needs one"
        );
    }

    /// The error source chain ends here and carries nothing of its own.
    ///
    /// # Why a chain is a rendering path
    ///
    /// `{:#}`-style reporters and `anyhow`-shaped printers walk `Error::source` and concatenate
    /// what they find. A cause attached here would be rendered by consumers that never called
    /// `detail()` at all — which is exactly how the database adapters' driver text was reaching
    /// logs before this phase's second correction round terminated those chains.
    #[test]
    fn the_error_chain_terminates_and_adds_nothing() {
        use core::error::Error as _;

        for (index, detail) in HttpErrorDetail::ALL.into_iter().enumerate() {
            let error = HttpError::new(HttpErrorKind::HandlerFailed, detail);
            assert!(
                error.source().is_none(),
                "variant {index} attached a source; a cause chained here is rendered by reporters \
                 that never asked for the detail"
            );
        }
    }

    #[test]
    fn statuses_match_the_published_contract() {
        assert_eq!(HttpErrorKind::BodyTooLarge.status(), 413);
        assert_eq!(HttpErrorKind::TimedOut.status(), 408);
        assert_eq!(HttpErrorKind::Unavailable.status(), 503);
        assert_eq!(HttpErrorKind::HostRejected.status(), 400);
        assert_eq!(HttpErrorKind::NotFound.status(), 404);

        // An IO failure while reading a body is NOT reported as over-limit. Asserted because the
        // two used to share `413`, and a status that names the wrong cause sends an operator to
        // the wrong investigation.
        assert_ne!(
            HttpErrorKind::BodyUnreadable.status(),
            HttpErrorKind::BodyTooLarge.status()
        );
    }

    #[test]
    fn every_kind_has_a_distinct_stable_code() {
        let kinds = [
            HttpErrorKind::HostRejected,
            HttpErrorKind::BodyTooLarge,
            HttpErrorKind::TimedOut,
            HttpErrorKind::Unavailable,
            HttpErrorKind::OriginRejected,
            HttpErrorKind::StateUnavailable,
            HttpErrorKind::HandlerFailed,
        ];
        let mut codes: Vec<&str> = kinds.iter().map(|kind| kind.code()).collect();
        codes.sort_unstable();
        let count = codes.len();
        codes.dedup();
        assert_eq!(codes.len(), count, "two kinds share a code");
    }
}
