//! v6-project — generated by renvor.

mod domain;
mod seed;

fn main() {
    println!("v6-project is running");
    println!("{} items", domain::all().len());
    // `src/entity.rs` and `src/repository.rs` are generated and idiomatic, but nothing compiles
    // them yet: they need `sea-orm`, and this project declares no dependencies so that
    // `renvor new` works offline. `Cargo.toml` names the four lines to add; then declare
    // `mod entity;` and `mod repository;` above and call into the repository from here.
    println!("persistence: seaorm, postgres (see src/entity.rs)");
}
