//! `renvor check` — validate a project without building it.
//!
//! FR-019. Parses `renvor.toml`, validates it, and reports **the field and the constraint** on
//! failure. "Invalid manifest" tells an operator nothing; "`project.name` must start with an ASCII
//! letter" tells them what to edit.

use serde::{Deserialize, Serialize};

use crate::exit::{CliError, Code, Exit};
use crate::output::Reporter;
use crate::paths::validate_project_name;

/// The `[renvor]` table.
#[derive(Debug, Deserialize, Serialize)]
struct RenvorTable {
    generator_version: String,
    template_version: String,
}

/// The `[project]` table — only the fields `check` validates.
#[derive(Debug, Deserialize, Serialize)]
struct ProjectTable {
    name: String,
    target: String,
    local_domain: String,
}

/// A generated `renvor.toml`.
#[derive(Debug, Deserialize, Serialize)]
struct Manifest {
    renvor: RenvorTable,
    project: ProjectTable,
}

/// Runs the command against a project directory.
///
/// # Errors
///
/// [`Code::ManifestInvalid`] with `details.field` and `details.constraint`.
pub fn run(reporter: &Reporter, path: &std::path::Path) -> Result<Exit, CliError> {
    let manifest_path = path.join("renvor.toml");
    let text = std::fs::read_to_string(&manifest_path).map_err(|error| {
        CliError::new(
            Code::ManifestInvalid,
            format!("`{}` could not be read: {error}", manifest_path.display()),
        )
        .with("field", "renvor.toml")
        .with("constraint", "must exist and be readable")
    })?;

    let manifest: Manifest = toml::from_str(&text).map_err(|error| {
        CliError::new(
            Code::ManifestInvalid,
            format!(
                "`{}` is not a valid renvor manifest: {error}",
                manifest_path.display()
            ),
        )
        .with("field", "renvor.toml")
        .with("constraint", "must parse as a renvor manifest")
    })?;

    let invalid = |field: &str, constraint: &str| {
        CliError::new(
            Code::ManifestInvalid,
            format!("`{field}` is invalid: {constraint}"),
        )
        .with("field", field.to_owned())
        .with("constraint", constraint.to_owned())
    };

    validate_project_name(&manifest.project.name)
        .map_err(|error| invalid("project.name", &error.message))?;

    if manifest.project.target != "api" {
        return Err(invalid(
            "project.target",
            "must be `api`; no other target is generated by this version",
        ));
    }
    if manifest.project.local_domain.is_empty() {
        return Err(invalid("project.local_domain", "must not be empty"));
    }
    if manifest.renvor.template_version.is_empty() {
        return Err(invalid("renvor.template_version", "must not be empty"));
    }

    let human = format!(
        "ok  {} (target {}, template version {})",
        manifest.project.name, manifest.project.target, manifest.renvor.template_version
    );
    Ok(reporter.finish(
        "check",
        &human,
        serde_json::json!({
            "name": manifest.project.name,
            "target": manifest.project.target,
            "templateVersion": manifest.renvor.template_version,
        }),
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::output::Format;

    fn reporter() -> Reporter {
        Reporter::new(Format::Human, true)
    }

    fn write(text: &str) -> tempfile::TempDir {
        let dir = tempfile::tempdir().expect("tempdir");
        std::fs::write(dir.path().join("renvor.toml"), text).expect("write");
        dir
    }

    const VALID: &str = r#"
[renvor]
generator_version = "0.0.0"
template_version = "1"

[project]
name = "commerce"
target = "api"
local_domain = "commerce.test"
"#;

    #[test]
    fn a_valid_manifest_passes() {
        // POSITIVE CONTROL for every rejection below.
        let dir = write(VALID);
        assert_eq!(run(&reporter(), dir.path()).expect("checks"), Exit::Success);
    }

    #[test]
    fn every_rejection_names_the_field_and_the_constraint() {
        // FR-019. A failure that says only "invalid" makes the operator bisect their own file.
        let cases = [
            (VALID.replace("commerce\"", "1bad\""), "project.name"),
            (VALID.replace("\"api\"", "\"full-stack\""), "project.target"),
            (VALID.replace("commerce.test", ""), "project.local_domain"),
            (
                VALID.replace("template_version = \"1\"", "template_version = \"\""),
                "renvor.template_version",
            ),
        ];
        for (text, field) in cases {
            let dir = write(&text);
            let error = run(&reporter(), dir.path()).unwrap_err();
            assert_eq!(error.code, Code::ManifestInvalid, "{field}");
            assert!(
                error
                    .details
                    .iter()
                    .any(|(k, v)| k == "field" && v == field),
                "expected field {field}, got {:?}",
                error.details
            );
            assert!(
                error
                    .details
                    .iter()
                    .any(|(k, v)| k == "constraint" && !v.is_empty()),
                "{field} reported no constraint"
            );
        }
    }

    #[test]
    fn a_missing_manifest_is_reported_as_such_rather_than_as_a_parse_error() {
        let dir = tempfile::tempdir().expect("tempdir");
        let error = run(&reporter(), dir.path()).unwrap_err();
        assert_eq!(error.code, Code::ManifestInvalid);
        assert!(
            error.message.contains("could not be read"),
            "{}",
            error.message
        );
    }

    #[test]
    fn check_never_builds_anything() {
        // FR-019 says "without building it". Asserted by the absence of any build artifact after
        // a successful check — a check that shelled out to cargo would leave `target/`.
        let dir = write(VALID);
        run(&reporter(), dir.path()).expect("checks");
        assert!(
            !dir.path().join("target").exists(),
            "check produced build output"
        );
    }
}
